Download button
aamay001/react-resume pull request #102
Opened 2020-10-07 20:22 UTC by jespicas

DownloadButton: Add Cypress Test 
Check if exist attribute download with resume.json
Check if href contains a value
![Screenshot from 2020-10-07 22-20-48](https://user-images.githubusercontent.com/3797505/95383524-98deb100-08eb-11eb-910d-6fb20adcf110.png)

2020-10-07 20:54 UTC, aamay001 requested changes
Please make the changes specified below.

2020-10-07 20:54 UTC, aamay001 commented on cypress/integration/components/Tools/Buttons/DownloadButton.spec.js
> +      .should('have.attr', 'href').and('include', 'data:text/plain;charset=utf-8,%7B%0A%09%22header%22%3A%20%7B%0A%09%09%22name%22%3A%20%22Your%20Name%22%2C%0A%09%09%22email%22%3A%20%22email%40domain
Please put the file data into a fixture.

2020-10-07 20:54 UTC, aamay001 commented on cypress/integration/components/Tools/Buttons/SaveToCloudButtons.spec.js
> +context('Click SaveToCloud buttons', () => {
This file should not be included in this PR.

2020-10-10 11:40 UTC, aamay001 requested changes
Tests are failing because the `SaveToCloudButtons.spec` file is still included in this PR. Those tests fail. Please remove the file from the PR.

2020-10-10 12:42 UTC, jespicas commented
> Tests are failing because the `SaveToCloudButtons.spec` file is still included in this PR. Those tests fail. Please remove the file from the PR.

Now not has this file and still failing

2020-10-10 13:32 UTC, aamay001 approved these changes
Thanks for making the changes. I can't figure out wh but, when the pipeline runs for your branch, it's not correctly populating a variable for Cypress. I ran the tests manually on your branch and they pass when I do that so I will merge your PR. Thanks for your contributions.

2020-10-10 13:33 UTC, merged